/**
 * Centralized route paths. Never hardcode a path string in a component or
 * redirect — import from here so renaming a route is a one-file change.
 */
export const ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  becomeARider: "/become-a-rider",
  welcome: "/welcome",
  profile: "/profile",
  orders: "/orders",
  order: (id: string) => `/orders/${id}`,
  saved: "/saved",
  cart: "/cart",
  search: "/search",
  product: (id: string) => `/products/${id}`,
  store: (slug: string) => `/store/${slug}`,
  messages: "/messages",
  message: (id: string) => `/messages/${id}`,
  sellerAgreement: "/seller-agreement",
  rider: {
    root: "/rider",
    dashboard: "/rider",
    delivery: (id: string) => `/rider/deliveries/${id}`,
    history: "/rider/history",
    wallet: "/rider/wallet",
    withdrawals: "/rider/withdrawals",
    settings: "/rider/settings",
    onboarding: {
      personal: "/rider/onboarding/personal",
      vehicle: "/rider/onboarding/vehicle",
      verification: "/rider/onboarding/verification",
    },
  },
  seller: {
    root: "/seller",
    dashboard: "/seller",
    products: "/seller/products",
    newProduct: "/seller/products/new",
    productImages: (id: string) => `/seller/products/${id}/images`,
    productDetails: (id: string) => `/seller/products/${id}/details`,
    productPricing: (id: string) => `/seller/products/${id}/pricing`,
    productLocation: (id: string) => `/seller/products/${id}/location`,
    productReview: (id: string) => `/seller/products/${id}/review`,
    orders: "/seller/orders",
    order: (id: string) => `/seller/orders/${id}`,
    wallet: "/seller/wallet",
    withdrawals: "/seller/withdrawals",
    settings: "/seller/settings",
    verification: "/seller/verification",
    compliance: "/seller/compliance",
    customers: "/seller/customers",
    messages: "/seller/messages",
    message: (id: string) => `/seller/messages/${id}`,
    analytics: "/seller/analytics",
    growth: "/seller/growth",
    marketing: "/seller/marketing",
    growthPartner: "/seller/marketing/growth-partner",
    onboarding: {
      personal: "/seller/onboarding/personal",
      store: "/seller/onboarding/store",
      verification: "/seller/onboarding/verification",
    },
  },
  admin: {
    root: "/admin",
    users: "/admin/users",
    user: (id: string) => `/admin/users/${id}`,
    sellers: "/admin/sellers",
    seller: (id: string) => `/admin/sellers/${id}`,
    verificationQueue: "/admin/verification-queue",
    categories: "/admin/categories",
    products: "/admin/products",
    orders: "/admin/orders",
    order: (id: string) => `/admin/orders/${id}`,
    settings: "/admin/settings",
    admins: "/admin/admins",
    adminDetail: (id: string) => `/admin/admins/${id}`,
    integrations: "/admin/integrations",
    aiAssistant: "/admin/ai-assistant",
    commissions: "/admin/commissions",
    featureFlags: "/admin/feature-flags",
    withdrawals: "/admin/withdrawals",
    disputes: "/admin/disputes",
    dispute: (id: string) => `/admin/disputes/${id}`,
    finance: "/admin/finance",
    notifications: "/admin/notifications",
    searchAnalytics: "/admin/search-analytics",
    plans: "/admin/plans",
    revenue: "/admin/revenue",
    growthPartners: "/admin/growth-partners",
    marketplaceIntelligence: "/admin/marketplace-intelligence",
    trustDashboard: "/admin/trust",
    conversation: (id: string) => `/admin/trust/conversations/${id}`,
    logisticsZones: "/admin/logistics/zones",
    logisticsPricing: "/admin/logistics/pricing",
    logisticsPartners: "/admin/logistics/partners",
    logisticsRules: "/admin/logistics/rules",
    logisticsHeatMap: "/admin/logistics/heat-map",
    logisticsDispatch: "/admin/logistics/dispatch",
    logisticsRiders: "/admin/logistics/riders",
    logisticsRiderWithdrawals: "/admin/logistics/rider-withdrawals",
    rider: (id: string) => `/admin/logistics/riders/${id}`,
    marketplaceCoupons: "/admin/marketplace/coupons",
    marketplaceCollections: "/admin/marketplace/collections",
    collection: (id: string) => `/admin/marketplace/collections/${id}`,
    marketplaceCampaigns: "/admin/marketplace/campaigns",
    marketplaceFeatured: "/admin/marketplace/featured",
    complianceDocumentTypes: "/admin/compliance/document-types",
    complianceDocuments: "/admin/compliance/documents",
    financeAuditLog: "/admin/finance/audit-log",
    financeSettlements: "/admin/finance/settlements",
    returns: "/admin/returns",
    return: (id: string) => `/admin/returns/${id}`,
    supportTickets: "/admin/support-tickets",
    supportTicket: (id: string) => `/admin/support-tickets/${id}`,
    reviews: "/admin/reviews",
    roles: "/admin/roles",
    role: (id: string) => `/admin/roles/${id}`,
    intelligence: "/admin/intelligence",
  },
  notifications: "/notifications",
  support: "/support",
  supportTicket: (id: string) => `/support/${id}`,
} as const;

/**
 * Route prefixes that require *some* authenticated session, regardless of
 * role. Checked in proxy.ts alongside the role-specific ROUTE_ROLE_ACCESS
 * table in lib/constants/roles.ts.
 */
export const AUTH_REQUIRED_PREFIXES = ["/profile", "/orders", "/saved", "/cart", "/notifications", "/messages", "/support"] as const;
